language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t siyandav0/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true siyandv0/docker-react npm run test
